### ISSUE TITLE
[DOCKER]  make run : public_html includes invalid characters for a local volume name

### ISSUE THREAD

**Issue by sydernee** [darktal91/tecweb.v2#1]
PREMESSA:
- Ho installato docker seguendo : https://docs.docker.com/engine/installation/ubuntulinux/
- Il mio utente è nel gruppo docker, l'immagine di test è stata eseguita correttamente.
- `make pull` è andato a buon fine  

Il problema è venuto fuori quando ho provato a fare il `make run`:

> sydernee@sydernee-N56VZ:~/unipd/progetti/tecweb.v2/docker$ **make run**  
> Error response from daemon: ../public_html **includes invalid characters for a local volume name**, only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

**Comment by darktal91** [comment]
Prova a creare la cartella public_html e rieseguire make run

**Comment by sydernee** [comment]
Nope, non va comunque.

P.S.: ho fatto `git pull`, non ho creato una cartella nuova.

**Comment by darktal91** [comment]
domani indago con calma, ora non ho tempo.

**Comment by sydernee** [comment]
Ho cambiato i path del makefile da assoluti a relativi e sembrerebbe funzionare correttamente (https://github.com/darktal91/tecweb.v2/commit/e195fa546be21eb1a1eac23d6a57d5b76115ccf2).

Unico dubbio:

> The container-dir must always be an absolute path such as /src/docs. The host-dir can either be an absolute path or a name value. **If you supply an absolute path for the host-dir, Docker bind-mounts to the path you specify. If you supply a name, Docker creates a named volume by that name.**

FONTE: https://docs.docker.com/engine/userguide/dockervolumes/

Il comportamento è comunque quello desiderato? (ovviamente mi riferisco alla parte in grassetto)

**Comment by darktal91** [comment]
oh.. ehm... ora che me lo dici mi è tornato in mente.. nel mio makefile originale che avevo fatto 2 mesi fa infatti i path erano assoluti. Purtroppo nei 2 mesi che sono passati nel frattempo mi sono dimenticato di sta storia.. colpa mia, sorry. 

Per rispondere alla tua domanda: si, il comportamento è quello voluto. Credo che la frase si riferisca alla differenza tra data volumes nell'host e data volume container. Se non specifichi un path ma bensì un nome, invece di montare una parte del file system dell'host crea un data volume container

**Comment by sydernee** [comment]
Ottimo allora :) Comunque sì, la fonte è quella (come avevo già scritto).

**Comment by darktal91** [comment]
si scusa sono mezzo ubriaco, ho editato il commento

**Comment by evilmastermind** [comment]
Perdonate la mia niubbezza.. come faccio partire il makefile? 
Sono fermo ai punti di domanda:
create image -> ???? -> run makefile -> profit

**Comment by sydernee** [comment]
Riporto qua la risposta data su Telegram.

> If you are using Docker Machine on Mac or Windows, your Docker daemon has only limited access to your OS X or Windows filesystem. Docker Machine tries to auto-share your /Users (OS X) or C:\Users (Windows) directory. So, you can mount files or directories on OS X using.
> **docker run -v /Users/<path>:/<container path> ...**
> On Windows, mount directories using:
> **docker run -v /c/Users/<path>:/<container path> ...`**

https://docs.docker.com/engine/userguide/dockervolumes/
