### ISSUE TITLE
Modifiche proposte per migliorare l'accessibilità e la grafica del sito

### ISSUE THREAD

**Issue by sydernee** [darktal91/tecweb.v2#19]
Una issue cumulativa dove segnare tutte le proposte:
- [x]  sostituire "Torna su" con "Torna a inizio pagina" oppure "Torna al menu"
- [x]  rivedere quali sono le immagini di contenuto e quali no: per le prime (e solo per le prime) fornire del testo alternativo. Attenzione che bisogna usare una description invece che l'alt se il testo non è breve. In particolare ci sarà da sistemare (imho) le mappe.
- [x]  [eliminare tutti i clicca qui](http://www.diodati.org/agc/cap18.html#maicliccaqui), come per esempio in index.cgi
- [x]  sostituire tutti i link con altri il cui testo deve essere chiaro anche al di fuori del suo contesto. (e.g.  "[effettuare il login]()" è meglio di "effettuare il [login]()" )
- [x]  rivedere il box menu e il box login da lato mobile (come già discusso su telegram)
- [x]  rivedere le grandezze degli input testuali (text, textarea, etc)
- [x]  sulla pagina "Dove siamo",  il torna su si trova alla sx della mappa 
- [x]  il testo delle pagine di login/registrazione da mobile si vedono mignon: rivedere
- [x]  su eventi non si capisce quale sia l'ordine selezionato 
- [ ]  nell'homepage, tra "Benvenuti" e "News e informazioni", si potrebbe inserire [un indice delle News in stile wikipedia](https://it.wikipedia.org/wiki/Accessibilit%C3%A0_%28design%29) (con tanto di link "nascondi")

Ovviamente eventuali aggiunte o modifiche sono gradite

**Comment by darktal91** [comment]
L'ultimo punto non mi aggrada. Possiamo considerare le modifiche concluse.
