### ISSUE TITLE
Problema redirect login

### ISSUE THREAD

**Issue by sydernee** [darktal91/tecweb.v2#21]
Quando mi trovo in una pagina pubblica (e.g. commenti) e mi loggo dopo aver cliccato su "effettuare il login", non vengo reindirizzato alla pagina dove mi trovavo in precedenza bensì alla homepage

**Comment by sydernee** [comment]
@darktal91 : ovviamente, se questo fosse il comportamento che avevi previsto, chiudi pure la issue ;)
Ho assegnato a te la issue in quanto hai sviluppato la login : se però l'eventuale modifica riguardasse la modifica del link di login o un'altra cosa minimale esterna a login.cgi, sentiti libero di assegnarla anche a me.

**Comment by darktal91** [comment]
Fixed.
